# Preprocessing

In [ ]:
# Import Library

import pandas as pd
import re
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data = '/content/drive/MyDrive/TA/Rev1/Rev1_output_labelling.csv'
news = pd.read_csv(data, encoding= 'unicode_escape')
news

tokoh                                              title  \
0    anies baswedan  Anies Bertemu Relawan Pendukungnya di Australi...   
1    anies baswedan  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    anies baswedan  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    anies baswedan  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    anies baswedan  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..              ...                                                ...   
877         prabowo  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878         prabowo  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879         prabowo  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880         prabowo  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881         prabowo  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                              date  \
0     Senin, 06 Mar 2023 10:15 WIB   
1     Senin, 06 Mar 2023 08:57 WIB   
2     Senin, 06 Mar 2023 09:00 WIB   
3     Senin, 06 Mar 2023 08:00 WIB   
4     Senin, 06 Mar 2023 08:55 WIB   
..                             ...   
877   Senin, 06 Mar 2023 14:13 WIB   
878   Senin, 06 Mar 2023 13:47 WIB   
879   Senin, 06 Mar 2023 16:18 WIB   
880  Selasa, 07 Mar 2023 06:41 WIB   
881   Senin, 06 Mar 2023 08:57 WIB   

                                           description  A  B  C  label  \
0    \-\n\nMantan Gubernur DKI Jakarta Anies Baswed...  1  1  0      0   
1    \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   
2    \-\n\nDalam pertemuannya di Hambalang, Bogor, ...  1  0  1      0   
3    \-\n\nRiuh soal izin mendirikan bangunan (IMB)... -1 -1 -1     -1   
4    \-\n\nBakal calon presiden dari Partai Gerindr...  1  0  0      0   
..                                                 ... .. .. ..    ...   
877  \-\n\nBakal calon presiden (Capres) Partai Ger...  1  0  1      0   
878  \-\n\nDua bakal calon presiden Prabowo Subiant...  1  0  0      0   
879  \-\n\nCalon presiden Partai Gerindra Prabowo S...  1 -1  0      0   
880  \-\n\nWacana duet Anies Baswedan dan Sandiaga ...  0  0  0      0   
881  \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   

     Rev1_label  
0             1  
1             1  
2             1  
3            -1  
4             0  
..          ...  
877           1  
878           0  
879           0  
880           0  
881           1  

[882 rows x 9 columns]

In [ ]:
Raw_data = news.drop(['date','A','B','C','label'], axis=1)

### Case folding

In [ ]:
def preprocessing(teks):
  teks = teks.lower()                               # lower case
  teks = re.sub(r'[-+]?[0-9]+', ' ', teks)           # number
  teks = re.sub(r"_", " ", teks)
  teks.replace('\\t'," ").replace('\\n'," ").replace('\\u'," ").replace('\\'," ")    # remove tab, new line, and back slice
  teks = re.sub(r'((http|https)\:\/\/)[a-zA-Z0-9\.\/\?\:@\-_=#]+\.([a-zA-Z]){2,6}([a-zA-Z0-9\.\&\/\?\:@\-_=#])*', " ", teks)
  ' '.join(re.sub("([@#][A-Za-z0-9]+)|(\w+:\/\/\S+)"," ", teks).split())            # remove mention, link, hashtag
  teks = re.sub(r'[^\w\s]',' ', teks)                # punctuation
  teks = re.sub('\s+',' ',teks)                     # multiple whitespace into single whitespace
  teks = re.sub(r"\b[a-zA-Z]\b", "", teks)                                             # single char
  teks.strip()                                                                      # whitespace leading & trailing
  return teks

In [ ]:
def rev_space(teks):
  teks = re.sub('\s+',' ',teks)
  return teks                    # multiple whitespace into single whitespace

### Tokenizing

In [ ]:
# import library word_tokenize & FreqDist from NLTK
from nltk.tokenize import word_tokenize
from nltk.probability import FreqDist
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
def word_tokenizing(teks):
    return word_tokenize(teks)

### stopwords

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def remove_stopwords(kata):
  stopwords_ind = stopwords.words('indonesian')
  stopwords_ind.extend(["yg", "dg", "rt", "dgn", "ny", "d", 'klo',
                       'kalo', 'amp', 'biar', 'bikin', 'bilang',
                       'gak', 'ga', 'krn', 'nya', 'nih', 'sih',
                       'si', 'tau', 'tdk', 'tuh', 'utk', 'ya',
                       'jd', 'jgn', 'sdh', 'aja', 'n', 't',
                       'nyg', 'hehe', 'pen', 'u', 'nan', 'loh', 'rt',
                       '&amp', 'yah', "detik", "detikjatim", "detikjateng",
                        "detikjabar", "detiksulsel", "detiksumbar", "detikbali",
                        "detikpapua", "detiksulteng", "detikmaluku", "detjatim",
                        "detikcom", "allahumma", "aamiin", "allah", "bismillah",
                        "20detik", "gambasvideo", 'simak', 'lengkap', 'sini', 'halaman','halaman selanjutnya'])
  stopwords_ind = set(stopwords_ind)
  return [word
            for word in kata
              if word not in stopwords_ind]

### Stemming

In [ ]:
!pip install Sastrawi
!pip install swifter
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import swifter

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 5.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 490.6/490.6 kB 9.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 49.0 MB/s eta 0:00:00
  Created wheel for swifter: filename=swifter-1.3.5-py3-none-any.whl size=16518 sha256=f9274c9ae976369f6e11c057f9b57a5f372464bddd041164962cde8a09d711e6
  Stored in directory: /root/.cache/pip/wheels/00/7e/8c/438ea309a16ef1a9130849060f962e0d2c4e94b8a4314d5919
Successfully built swifter


In [ ]:
factory = StemmerFactory()
stemmer = factory.create_stemmer()

In [ ]:
def stemmed_wrapper(words):
  words = stemmer.stem(words)
  return words

In [ ]:
term_dict = {}

# Lexicon News

In [ ]:
def score(text):
      neg_score = 0
      pos_score = 0
      net_score = 0
      for word in text:
          if (word in lexicon_positive):
              pos_score = pos_score + lexicon_positive[word]
      for word in text:
          if (word in lexicon_negative):
              neg_score = neg_score + lexicon_negative[word]

      score = pos_score + neg_score

      return score

In [ ]:
def value(text):
      neg_score = 0
      pos_score = 0
      net_score = 0
      for word in text:
          if (word in lexicon_positive):
              pos_score = pos_score + lexicon_positive[word]
      for word in text:
          if (word in lexicon_negative):
              neg_score = neg_score + lexicon_negative[word]

      score = pos_score + neg_score

      polarity = 0
      if (score > 1):
          polarity = 1
      elif (score < 0):
          polarity = -1
      else:
          polarity = 0

      return polarity

# TFIDF

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

# Klasifikasi

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.svm import LinearSVC, SVC
from sklearn.linear_model import LogisticRegression

# Evaluasi

In [ ]:
def model_Evaluate(model):

    y_pred = model.predict(x_test)

    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

# All Data (Title + Description)

In [ ]:
all_news = news.copy()

In [ ]:
all_news['all'] = all_news['title'] + all_news['description']

In [ ]:
all_news['case folding_all'] = all_news['all'].apply(preprocessing)
all_news['case folding_all'] = all_news['case folding_all'].apply(rev_space)
all_news['tokenizing_all'] = all_news['case folding_all'].apply(word_tokenizing)
all_news['stopwords_removal_all'] = all_news['tokenizing_all'].apply(remove_stopwords)


In [ ]:
for document in all_news['stopwords_removal_all']:
    for term in document:
        if term not in term_dict:
            term_dict[term] = ' '

In [ ]:
for term in term_dict:
    term_dict[term] = stemmed_wrapper(term)
    #print(term,":" ,term_dict[term])

In [ ]:
def stemmingText(document):
    return [term_dict[term] for term in document]

In [ ]:
all_news['stemming_all'] = all_news['stopwords_removal_all'].apply(stemmingText)

In [ ]:
for idx, row in all_news.iterrows():
  while("" in all_news['stemming_all'][idx]):
    all_news['stemming_all'][idx].remove("")

# Word Embedding

In [ ]:
all_news['stemming_all_string'] = [','.join(map(str, l)) for l in all_news['stemming_all']]
all_news['stemming_all_string']

0      anies,temu,rawan,dukung,australia,bahas,mantan...
1      pks,bahagia,prabowo,temu,paloh,bravo,kian,mulu...
2      bos,ppi,nilai,prabowo,paloh,pisah,jalan,temu,h...
3      riuh,imb,era,anies,ungkit,pdip,bakar,lahan,plu...
4      prabowo,anies,hadap,rakyat,pilih,calon,preside...
                             ...                        
877    prabowo,lawan,anies,baswedan,pilpres,peta,kuat...
878    kini,peta,kuat,prabowo,anies,jelang,pilpres,ca...
879    nasdem,tafsir,sendiri,prabowo,hadap,anies,calo...
880    duet,anies,sandi,nilai,wacana,duet,anies,baswe...
881    pks,bahagia,prabowo,temu,paloh,bravo,kian,mulu...
Name: stemming_all_string, Length: 882, dtype: object

In [ ]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(all_news['stemming_all_string'])
vectorizer.get_feature_names_out()

array(['aa', 'aaa', 'aaaaa', ..., 'zulkifliemansyah', 'zumarni', 'zumba'],
      dtype=object)

In [ ]:
df = pd.DataFrame(X.toarray(), columns = vectorizer.get_feature_names_out())
df

aa  aaa  aaaaa  aaaaaagggggghhhhhh  aaaaaminn  aadc  aam  aan  aaron  \
0    0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
1    0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
2    0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
3    0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
4    0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
..   ...  ...    ...                 ...        ...   ...  ...  ...    ...   
877  0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
878  0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
879  0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
880  0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   
881  0.0  0.0    0.0                 0.0        0.0   0.0  0.0  0.0    0.0   

     abacus  ...  zukifli  zul  zulfan  zulhaqqi  zulhas  zulkieflimansyah  \
0       0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
1       0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
2       0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
3       0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
4       0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
..      ...  ...      ...  ...     ...       ...     ...               ...   
877     0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
878     0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
879     0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
880     0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   
881     0.0  ...      0.0  0.0     0.0       0.0     0.0               0.0   

     zulkifli  zulkifliemansyah  zumarni  zumba  
0         0.0               0.0      0.0    0.0  
1         0.0               0.0      0.0    0.0  
2         0.0               0.0      0.0    0.0  
3         0.0               0.0      0.0    0.0  
4         0.0               0.0      0.0    0.0  
..        ...               ...      ...    ...  
877       0.0               0.0      0.0    0.0  
878       0.0               0.0      0.0    0.0  
879       0.0               0.0      0.0    0.0  
880       0.0               0.0      0.0    0.0  
881       0.0               0.0      0.0    0.0  

[882 rows x 11609 columns]

# Min

In [ ]:
lexicon_positive = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_pos_minvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_positive[row[0]] = float(row[1])

lexicon_negative = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_neg_minvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_negative[row[0]] = float(row[1])

In [ ]:
all_news['score_Sentil'] = all_news['stemming_all'].apply(score)
all_news['value_Sentil'] = all_news['stemming_all'].apply(value)
all_news

tokoh                                              title  \
0    anies baswedan  Anies Bertemu Relawan Pendukungnya di Australi...   
1    anies baswedan  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    anies baswedan  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    anies baswedan  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    anies baswedan  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..              ...                                                ...   
877         prabowo  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878         prabowo  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879         prabowo  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880         prabowo  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881         prabowo  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                              date  \
0     Senin, 06 Mar 2023 10:15 WIB   
1     Senin, 06 Mar 2023 08:57 WIB   
2     Senin, 06 Mar 2023 09:00 WIB   
3     Senin, 06 Mar 2023 08:00 WIB   
4     Senin, 06 Mar 2023 08:55 WIB   
..                             ...   
877   Senin, 06 Mar 2023 14:13 WIB   
878   Senin, 06 Mar 2023 13:47 WIB   
879   Senin, 06 Mar 2023 16:18 WIB   
880  Selasa, 07 Mar 2023 06:41 WIB   
881   Senin, 06 Mar 2023 08:57 WIB   

                                           description  A  B  C  label  \
0    \-\n\nMantan Gubernur DKI Jakarta Anies Baswed...  1  1  0      0   
1    \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   
2    \-\n\nDalam pertemuannya di Hambalang, Bogor, ...  1  0  1      0   
3    \-\n\nRiuh soal izin mendirikan bangunan (IMB)... -1 -1 -1     -1   
4    \-\n\nBakal calon presiden dari Partai Gerindr...  1  0  0      0   
..                                                 ... .. .. ..    ...   
877  \-\n\nBakal calon presiden (Capres) Partai Ger...  1  0  1      0   
878  \-\n\nDua bakal calon presiden Prabowo Subiant...  1  0  0      0   
879  \-\n\nCalon presiden Partai Gerindra Prabowo S...  1 -1  0      0   
880  \-\n\nWacana duet Anies Baswedan dan Sandiaga ...  0  0  0      0   
881  \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   

     Rev1_label                                                all  \
0             1  Anies Bertemu Relawan Pendukungnya di Australi...   
1             1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2             1  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3            -1  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4             0  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..          ...                                                ...   
877           1  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878           0  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879           0  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880           0  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881           1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                                      case folding_all  \
0    anies bertemu relawan pendukungnya di australi...   
1    pks bahagia prabowo bertemu paloh bravo kian m...   
2    bos ppi nilai prabowo dan paloh sudah siap pis...   
3    riuh imb era anies diungkit pdip usai kebakara...   
4    prabowo soal anies siap hadapi rakyat yang mem...   
..                                                 ...   
877  prabowo lawan anies baswedan di pilpres begini...   
878  terkini peta kekuatan prabowo dan anies jelang...   
879  nasdem punya tafsir tersendiri soal prabowo si...   
880  duet anies sandi dinilai kecil kemungkinan ter...   
881  pks bahagia prabowo bertemu paloh bravo kian m...   

                                        tokenizing_all  \
0    [anies, bertemu, relawan, pendukungnya, di, au...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [bos, ppi, nilai, prabowo, dan, paloh, sudah, ...   
3    [riu

In [ ]:
all_news.drop(['date','A','B','C','label'], axis=1)

tokoh                                              title  \
0    anies baswedan  Anies Bertemu Relawan Pendukungnya di Australi...   
1    anies baswedan  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    anies baswedan  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    anies baswedan  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    anies baswedan  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..              ...                                                ...   
877         prabowo  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878         prabowo  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879         prabowo  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880         prabowo  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881         prabowo  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                                           description  Rev1_label  \
0    \-\n\nMantan Gubernur DKI Jakarta Anies Baswed...           1   
1    \-\n\nKetum Gerindra Prabowo Subianto bertemu ...           1   
2    \-\n\nDalam pertemuannya di Hambalang, Bogor, ...           1   
3    \-\n\nRiuh soal izin mendirikan bangunan (IMB)...          -1   
4    \-\n\nBakal calon presiden dari Partai Gerindr...           0   
..                                                 ...         ...   
877  \-\n\nBakal calon presiden (Capres) Partai Ger...           1   
878  \-\n\nDua bakal calon presiden Prabowo Subiant...           0   
879  \-\n\nCalon presiden Partai Gerindra Prabowo S...           0   
880  \-\n\nWacana duet Anies Baswedan dan Sandiaga ...           0   
881  \-\n\nKetum Gerindra Prabowo Subianto bertemu ...           1   

                                                   all  \
0    Anies Bertemu Relawan Pendukungnya di Australi...   
1    PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..                                                 ...   
877  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                                      case folding_all  \
0    anies bertemu relawan pendukungnya di australi...   
1    pks bahagia prabowo bertemu paloh bravo kian m...   
2    bos ppi nilai prabowo dan paloh sudah siap pis...   
3    riuh imb era anies diungkit pdip usai kebakara...   
4    prabowo soal anies siap hadapi rakyat yang mem...   
..                                                 ...   
877  prabowo lawan anies baswedan di pilpres begini...   
878  terkini peta kekuatan prabowo dan anies jelang...   
879  nasdem punya tafsir tersendiri soal prabowo si...   
880  duet anies sandi dinilai kecil kemungkinan ter...   
881  pks bahagia prabowo bertemu paloh bravo kian m...   

                                        tokenizing_all  \
0    [anies, bertemu, relawan, pendukungnya, di, au...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [bos, ppi, nilai, prabowo, dan, paloh, sudah, ...   
3    [riuh, imb, era, anies, diungkit, pdip, usai, ...   
4    [prabowo, soal, anies, siap, hadapi, rakyat, y...   
..                                                 ...   
877  [prabowo, lawan, anies, baswedan, di, pilpres,...   
878  [terkini, peta, kekuatan, prabowo, dan, anies,...   
879  [nasdem, punya, tafsir, tersendiri, soal, prab...   
880  [duet, anies, sandi, dinilai, kecil, kemungkin...   
881  [pks, bahagia, prabowo, bertemu, paloh, bravo,...   

                                 stopwords_removal_all  \
0    [anies, bertemu, relawan, pendukungnya, austra...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [bos, ppi, nil

In [ ]:
x = all_news['value_Sentil'].values.reshape(-1, 1)
y = all_news['Rev1_label'].values.reshape(-1, 1)
y1 = all_news['Rev1_label']

## Hasil akurasi tanpa TFIDF dan ML

In [ ]:
accuracy_score(x,y)

0.21428571428571427

## Hasil akurasi ML tanpa TFIDF

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y1, test_size=0.2 , random_state = 0)

In [ ]:
LSVM = LinearSVC(random_state=0)
LSVM.fit(x_train,y_train)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.73      0.17      0.27        48
           0       0.00      0.00      0.00        57
           1       0.42      0.97      0.59        72

    accuracy                           0.44       177
   macro avg       0.38      0.38      0.29       177
weighted avg       0.37      0.44      0.31       177

[[ 8  0 40]
 [ 1  0 56]
 [ 2  0 70]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
LR = LogisticRegression()
LR.fit(x_train, y_train)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.73      0.17      0.27        48
           0       0.00      0.00      0.00        57
           1       0.42      0.97      0.59        72

    accuracy                           0.44       177
   macro avg       0.38      0.38      0.29       177
weighted avg       0.37      0.44      0.31       177

[[ 8  0 40]
 [ 1  0 56]
 [ 2  0 70]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Hasil akurasi TFIDF + Lexicon + ML

In [ ]:
df_after_lexicon = df.copy()

In [ ]:
bobot_total = []

for idx, row in df.iterrows():
    # for kata, bobot in row.iteritems():
    for kata in all_news['stemming_all'][idx]:
      bobot_baris = 0
      if (kata in list(lexicon_positive.keys())):
        # print(kata)
        bobot_baris += row[kata] * lexicon_positive[kata]

      if (kata in list(lexicon_negative.keys())):
        bobot_baris += row[kata] * lexicon_negative[kata]
      print(kata, bobot_baris)
      df_after_lexicon[kata][idx] = bobot_baris
        # news['score']
    print("------------------------------------------------", idx)

Streaming output truncated to the last 5000 lines.
sebut 0
lobi 0
lobi 0
inget 0
proses 0
lobi 0
paham 0
sikap 0
kondisi 0
wiranto 0
istana 0
negara 0
jl 0
veteran 0
jakarta 0
pusat 0
rabu 0
gambas 0
video 0
------------------------------------------------ 852
prabowo 0
gentar 0.0
hadap 0
anies 0
pilpres 0
rakyat 0
milih 0
prabowo 0
harga 0
putus 0
partai 0
nasdem 0
calon 0
anies 0
baswedan 0
capres 0
pilpres 0
tum 0
partai 0
gerindra 0
gentar 0.0
hadap 0
anies 0
rakyat 0
pilih -0.02635636820385884
------------------------------------------------ 853
warga 0
lampung 0
semut 0
pesta 0
rakyat 0
muzani 0
salam 0
prabowo 0
sekjen 0
partai 0
gerindra 0
ahmad 0
muzani 0
hadir 0
acara 0
jalan 0
sehat 0.0
pesta 0
rakyat 0
dpd 0
gerindra 0
lampung 0
warga 0
semut 0
gelar 0
pesta 0
rakyat 0
gerindra 0
lampung 0
acara 0
gelar 0
stadion 0
pahoman 0
minggu 0
pesta 0
rakyat 0
rangkai 0
ingat 0
hut 0
partai 0
gerindra 0
februari 0
terang -0.001926268131489501
tulis 0
gerindra 0
puluh 0
ribu 0
masyara

In [ ]:
# x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon,y, test_size=0.2 , random_state = 0)
x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon,y1, test_size=0.2 , random_state = 0)

In [ ]:
LSVM.fit(x_train,y_train)
predictions_svm = LSVM.predict(x_test)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svm_sentil_min = {'pred': predictions_svm, 'label': y_test}
svm_sentil_min = pd.DataFrame(svm_sentil_min)
svm_sentil_min

pred  label
150     1      0
406     1      0
513     1     -1
101     1      1
584     1     -1
..    ...    ...
362     1      1
367     1     -1
264     1     -1
320     1      0
466     1      1

[177 rows x 2 columns]

In [ ]:
merge_sentil_min_svm = svm_sentil_min.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_sentil_min_svm

pred  label                                   case folding_all
150     1      0  erick thohir rapat bareng pertamina bahas depo...
406     1      0  deretan tokoh potensial pilwakot bandung raffi...
513     1     -1  prilly latuconsina berusaha hibur oma saat kum...
101     1      1  momen presiden pks pakaikan peci ke anies usai...
584     1     -1  buya syafii pernah kena mental tapi ia bertumb...
..    ...    ...                                                ...
362     1      1  persib bakal penuh energi dengan daisuke sato ...
367     1     -1  ressa herlambang bangkrut sampai pinjam uang k...
264     1     -1   tembolok belum kering kapan suara lucinta lun...
320     1      0  nggak cuma prilly syahrini juga sebut tarif rp...
466     1      1  jadi dosen fisipol ugm prilly cerita caranya t...

[177 rows x 3 columns]

In [ ]:
merge_sentil_min_svm.to_csv('output_pred_minSVMSentil.csv')

In [ ]:
LR.fit(x_train, y_train)
predictions_lg = LR.predict(x_test)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
lg_sentil_min = {'pred': predictions_lg, 'label': y_test}
lg_sentil_min = pd.DataFrame(lg_sentil_min)
lg_sentil_min

pred  label
150     1      0
406     1      0
513     1     -1
101     1      1
584     1     -1
..    ...    ...
362     1      1
367     1     -1
264     1     -1
320     1      0
466     1      1

[177 rows x 2 columns]

In [ ]:
merge_lg_sentil_min = lg_sentil_min.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_lg_sentil_min

pred  label                                   case folding_all
150     1      0  erick thohir rapat bareng pertamina bahas depo...
406     1      0  deretan tokoh potensial pilwakot bandung raffi...
513     1     -1  prilly latuconsina berusaha hibur oma saat kum...
101     1      1  momen presiden pks pakaikan peci ke anies usai...
584     1     -1  buya syafii pernah kena mental tapi ia bertumb...
..    ...    ...                                                ...
362     1      1  persib bakal penuh energi dengan daisuke sato ...
367     1     -1  ressa herlambang bangkrut sampai pinjam uang k...
264     1     -1   tembolok belum kering kapan suara lucinta lun...
320     1      0  nggak cuma prilly syahrini juga sebut tarif rp...
466     1      1  jadi dosen fisipol ugm prilly cerita caranya t...

[177 rows x 3 columns]

In [ ]:
merge_lg_sentil_min.to_csv('output_pred_minLGSentil.csv')

## cross validation svm

In [ ]:
from sklearn.model_selection import cross_val_score

# Perform cross-validation
scores = cross_val_score(LSVM,df_after_lexicon,y, cv=5)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

In [ ]:
print("Cross-validation scores: ", scores)
print("Akurasi rata-rata:", scores.mean())

Cross-validation scores:  [0.46892655 0.46327684 0.46590909 0.46590909 0.46590909]
Akurasi rata-rata: 0.46598613251155624


## hyperparameter svm

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid_svm = {
    'C': [0.1, 1, 10],
    'max_iter': [100, 1000, 10000],
    'penalty': ['l1', 'l2'],
    'loss': ['hinge', 'squared_hinge'],
}

# Inisialisasi GridSearchCV
grid_search = GridSearchCV(LSVM, param_grid_svm, cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  w

Kombinasi Hyperparameter Terbaik:
{'C': 1, 'loss': 'hinge', 'max_iter': 1000, 'penalty': 'l2'}


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [ ]:
# Data training dan testing
X_train, X_test, y_train, y_test = train_test_split(df_after_lexicon, y, test_size=0.2, random_state=0) #digunakan random state = 0 supaya tidak berubah data yang akan diuji coba

# Inisialisasi model dengan kombinasi hyperparameter terbaik
svm_model = LinearSVC(C=1, max_iter=1000, penalty='l2', loss='hinge')

# Melatih model dengan data training
svm_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = svm_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


Akurasi model: 45.76%


## cross validation logistic regression

In [ ]:
scores_lg = cross_val_score(LR,df_after_lexicon,y, cv=5)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

In [ ]:
print("Cross-validation scores: ", scores_lg)
print("Akurasi rata-rata:", scores_lg.mean())

Cross-validation scores:  [0.46892655 0.46327684 0.46590909 0.46590909 0.46590909]
Akurasi rata-rata: 0.46598613251155624


## hyperparameter logistic regression

In [ ]:
# Set hyperparameter yang akan diuji
logreg = LogisticRegression(max_iter=1000)
param_grid_lr = {
    'C': [0.1, 1, 10],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear', 'lbfgs']
}

# Inisialisasi GridSearchCV
grid_search = GridSearchCV(logreg, param_grid_lr, cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:378: FitFailedWarning: 
15 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 1162, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py", line 54, in _check_solver
    raise ValueError(
ValueError: Solve

Kombinasi Hyperparameter Terbaik:
{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}


In [ ]:
# Inisialisasi model dengan kombinasi hyperparameter terbaik
logreg_model = LogisticRegression(C=10, penalty='l2', solver='liblinear')

# Melatih model dengan data training
logreg_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = logreg_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

Akurasi model: 40.68%


# Max

In [ ]:
lexicon_positive = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_pos_bigvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_positive[row[0]] = float(row[1])

lexicon_negative = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_neg_bigvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_negative[row[0]] = float(row[1])

In [ ]:
all_news['score_max_sentil'] = all_news['stemming_all'].apply(score)
all_news['value_max_sentil'] = all_news['stemming_all'].apply(value)
all_news

tokoh                                              title  \
0    anies baswedan  Anies Bertemu Relawan Pendukungnya di Australi...   
1    anies baswedan  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    anies baswedan  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    anies baswedan  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    anies baswedan  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..              ...                                                ...   
877         prabowo  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878         prabowo  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879         prabowo  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880         prabowo  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881         prabowo  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                              date  \
0     Senin, 06 Mar 2023 10:15 WIB   
1     Senin, 06 Mar 2023 08:57 WIB   
2     Senin, 06 Mar 2023 09:00 WIB   
3     Senin, 06 Mar 2023 08:00 WIB   
4     Senin, 06 Mar 2023 08:55 WIB   
..                             ...   
877   Senin, 06 Mar 2023 14:13 WIB   
878   Senin, 06 Mar 2023 13:47 WIB   
879   Senin, 06 Mar 2023 16:18 WIB   
880  Selasa, 07 Mar 2023 06:41 WIB   
881   Senin, 06 Mar 2023 08:57 WIB   

                                           description  A  B  C  label  \
0    \-\n\nMantan Gubernur DKI Jakarta Anies Baswed...  1  1  0      0   
1    \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   
2    \-\n\nDalam pertemuannya di Hambalang, Bogor, ...  1  0  1      0   
3    \-\n\nRiuh soal izin mendirikan bangunan (IMB)... -1 -1 -1     -1   
4    \-\n\nBakal calon presiden dari Partai Gerindr...  1  0  0      0   
..                                                 ... .. .. ..    ...   
877  \-\n\nBakal calon presiden (Capres) Partai Ger...  1  0  1      0   
878  \-\n\nDua bakal calon presiden Prabowo Subiant...  1  0  0      0   
879  \-\n\nCalon presiden Partai Gerindra Prabowo S...  1 -1  0      0   
880  \-\n\nWacana duet Anies Baswedan dan Sandiaga ...  0  0  0      0   
881  \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   

     Rev1_label                                                all  \
0             1  Anies Bertemu Relawan Pendukungnya di Australi...   
1             1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2             1  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3            -1  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4             0  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..          ...                                                ...   
877           1  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878           0  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879           0  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880           0  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881           1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                                      case folding_all  \
0    anies bertemu relawan pendukungnya di australi...   
1    pks bahagia prabowo bertemu paloh bravo kian m...   
2    bos ppi nilai prabowo dan paloh sudah siap pis...   
3    riuh imb era anies diungkit pdip usai kebakara...   
4    prabowo soal anies siap hadapi rakyat yang mem...   
..                                                 ...   
877  prabowo lawan anies baswedan di pilpres begini...   
878  terkini peta kekuatan prabowo dan anies jelang...   
879  nasdem punya tafsir tersendiri soal prabowo si...   
880  duet anies sandi dinilai kecil kemungkinan ter...   
881  pks bahagia prabowo bertemu paloh bravo kian m...   

                                        tokenizing_all  \
0    [anies, bertemu, relawan, pendukungnya, di, au...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [bos, ppi, nilai, prabowo, dan, paloh, sudah, ...   
3    [riu

## Hasil akurasi tanpa TFIDF dan ML

In [ ]:
i = all_news['value_max_sentil'].values.reshape(-1, 1)
accuracy_score(i,y)

0.46598639455782315

## Hasil akurasi ML tanpa TFIDF

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(i,y, test_size=0.2 , random_state = 0)

In [ ]:
LSVM.fit(x_train,y_train)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precisio

In [ ]:
LR.fit(x_train, y_train)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precisio

## Hasil akurasi TFIDF + Lexicon + ML

In [ ]:
df_after_lexicon_max = df.copy()

In [ ]:
bobot_total = []

for idx, row in df.iterrows():
    # for kata, bobot in row.iteritems():
    for kata in all_news['stemming_all'][idx]:
      bobot_baris = 0
      if (kata in list(lexicon_positive.keys())):
        # print(kata)
        bobot_baris += row[kata] * lexicon_positive[kata]

      if (kata in list(lexicon_negative.keys())):
        bobot_baris += row[kata] * lexicon_negative[kata]
      print(kata, bobot_baris)
      df_after_lexicon_max[kata][idx] = bobot_baris
        # news['score']
    print("------------------------------------------------", idx)

Streaming output truncated to the last 5000 lines.
sebut 0
lobi 0
lobi 0
inget 0
proses 0
lobi 0
paham 0
sikap 0
kondisi 0
wiranto 0
istana 0
negara 0
jl 0
veteran 0
jakarta 0
pusat 0
rabu 0
gambas 0
video 0
------------------------------------------------ 852
prabowo 0
gentar -0.2754730344224693
hadap 0
anies 0
pilpres 0
rakyat 0
milih 0
prabowo 0
harga 0
putus 0
partai 0
nasdem 0
calon 0
anies 0
baswedan 0
capres 0
pilpres 0
tum 0
partai 0
gerindra 0
gentar -0.2754730344224693
hadap 0
anies 0
rakyat 0
pilih 0.03268189657278496
------------------------------------------------ 853
warga 0
lampung 0
semut 0
pesta 0
rakyat 0
muzani 0
salam 0
prabowo 0
sekjen 0
partai 0
gerindra 0
ahmad 0
muzani 0
hadir 0
acara 0
jalan 0
sehat 0.0388025551097781
pesta 0
rakyat 0
dpd 0
gerindra 0
lampung 0
warga 0
semut 0
gelar 0
pesta 0
rakyat 0
gerindra 0
lampung 0
acara 0
gelar 0
stadion 0
pahoman 0
minggu 0
pesta 0
rakyat 0
rangkai 0
ingat 0
hut 0
partai 0
gerindra 0
februari 0
terang 0.009105994803404

In [ ]:
#x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon_max,y, test_size=0.2 , random_state = 0)
x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon_max,y1, test_size=0.2 , random_state = 0)

In [ ]:
LSVM.fit(x_train,y_train)
predictions_svm = LSVM.predict(x_test)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.86      0.12      0.22        48
           0       0.50      0.02      0.03        57
           1       0.42      0.99      0.59        72

    accuracy                           0.44       177
   macro avg       0.59      0.38      0.28       177
weighted avg       0.57      0.44      0.31       177

[[ 6  1 41]
 [ 0  1 56]
 [ 1  0 71]]


In [ ]:
svm_sentil_max = {'pred': predictions_svm, 'label': y_test}
svm_sentil_max = pd.DataFrame(svm_sentil_max)
merge_svm_sentil_max = svm_sentil_max.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_svm_sentil_max.to_csv('output_pred_maxSVMSentil.csv')

In [ ]:
LR.fit(x_train, y_train)
predictions_LR = LR.predict(x_test)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
LR_sentil_max = {'pred': predictions_LR, 'label': y_test}
LR_sentil_max = pd.DataFrame(LR_sentil_max)
merge_LR_sentil_max = LR_sentil_max.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_LR_sentil_max.to_csv('output_pred_maxLRSentil.csv')

## cross validation svm

In [ ]:
scores_max = cross_val_score(LSVM,df_after_lexicon_max,y1, cv=5)

In [ ]:
print("Cross-validation scores: ", scores_max)
print("Akurasi rata-rata:", scores_max.mean())

Cross-validation scores:  [0.44067797 0.47457627 0.46590909 0.46022727 0.48295455]
Akurasi rata-rata: 0.4648690292758089


## hyperparameter svm

In [ ]:
grid_search = GridSearchCV(LSVM, param_grid_svm, cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  w

Kombinasi Hyperparameter Terbaik:
{'C': 10, 'loss': 'squared_hinge', 'max_iter': 1000, 'penalty': 'l2'}


In [ ]:
# Data training dan testing
X_train, X_test, y_train, y_test = train_test_split(df_after_lexicon_max, y, test_size=0.2, random_state=0) #digunakan random state = 0 supaya tidak berubah data yang akan diuji coba

# Inisialisasi model dengan kombinasi hyperparameter terbaik
svm_model = LinearSVC(C=10, max_iter=1000, penalty='l2', loss='squared_hinge')

# Melatih model dengan data training
svm_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = svm_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

Akurasi model: 54.80%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


## cross validation logistic regression

In [ ]:
scores_lg_max = cross_val_score(LR,df_after_lexicon_max,y1, cv=5)

In [ ]:
print("Cross-validation scores: ", scores_lg_max)
print("Akurasi rata-rata:", scores_lg_max.mean())

Cross-validation scores:  [0.46892655 0.46327684 0.46590909 0.46590909 0.46590909]
Akurasi rata-rata: 0.46598613251155624


## hyperparameter logistic regression

In [ ]:
# Inisialisasi GridSearchCV
grid_search = GridSearchCV(logreg, param_grid_lr , cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

Kombinasi Hyperparameter Terbaik:
{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Inisialisasi model dengan kombinasi hyperparameter terbaik
logreg_model = LogisticRegression(C=10, penalty='l1', solver='liblinear')

# Melatih model dengan data training
logreg_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = logreg_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

Akurasi model: 55.93%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


# Mean

In [ ]:
lexicon_positive = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_pos_meanvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_positive[row[0]] = float(row[1])

lexicon_negative = dict()
import csv
with open('/content/drive/MyDrive/TA/Rev2/Dataset Sentil/SenTil_neg_meanvalue_v1.csv', 'r') as csvfile:
  reader = csv.reader(csvfile, delimiter=',')
  next(reader)
  for row in reader:
    lexicon_negative[row[0]] = float(row[1])

In [ ]:
all_news['score_mean_sentil'] = all_news['stemming_all'].apply(score)
all_news['value_mean_sentil'] = all_news['stemming_all'].apply(value)
all_news

tokoh                                              title  \
0    anies baswedan  Anies Bertemu Relawan Pendukungnya di Australi...   
1    anies baswedan  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   
2    anies baswedan  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...   
3    anies baswedan  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...   
4    anies baswedan  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...   
..              ...                                                ...   
877         prabowo  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...   
878         prabowo  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...   
879         prabowo  NasDem Punya Tafsir Tersendiri soal Prabowo Si...   
880         prabowo  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...   
881         prabowo  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...   

                              date  \
0     Senin, 06 Mar 2023 10:15 WIB   
1     Senin, 06 Mar 2023 08:57 WIB   
2     Senin, 06 Mar 2023 09:00 WIB   
3     Senin, 06 Mar 2023 08:00 WIB   
4     Senin, 06 Mar 2023 08:55 WIB   
..                             ...   
877   Senin, 06 Mar 2023 14:13 WIB   
878   Senin, 06 Mar 2023 13:47 WIB   
879   Senin, 06 Mar 2023 16:18 WIB   
880  Selasa, 07 Mar 2023 06:41 WIB   
881   Senin, 06 Mar 2023 08:57 WIB   

                                           description  A  B  C  label  \
0    \-\n\nMantan Gubernur DKI Jakarta Anies Baswed...  1  1  0      0   
1    \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   
2    \-\n\nDalam pertemuannya di Hambalang, Bogor, ...  1  0  1      0   
3    \-\n\nRiuh soal izin mendirikan bangunan (IMB)... -1 -1 -1     -1   
4    \-\n\nBakal calon presiden dari Partai Gerindr...  1  0  0      0   
..                                                 ... .. .. ..    ...   
877  \-\n\nBakal calon presiden (Capres) Partai Ger...  1  0  1      0   
878  \-\n\nDua bakal calon presiden Prabowo Subiant...  1  0  0      0   
879  \-\n\nCalon presiden Partai Gerindra Prabowo S...  1 -1  0      0   
880  \-\n\nWacana duet Anies Baswedan dan Sandiaga ...  0  0  0      0   
881  \-\n\nKetum Gerindra Prabowo Subianto bertemu ...  1  1  1      1   

     Rev1_label                                                all  ...  \
0             1  Anies Bertemu Relawan Pendukungnya di Australi...  ...   
1             1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...  ...   
2             1  Bos PPI Nilai Prabowo dan Paloh Sudah Siap Pis...  ...   
3            -1  Riuh IMB Era Anies Diungkit PDIP Usai Kebakara...  ...   
4             0  Prabowo soal Anies: Siap Hadapi, Rakyat yang M...  ...   
..          ...                                                ...  ...   
877           1  Prabowo 'Lawan' Anies Baswedan di Pilpres 2024...  ...   
878           0  Terkini! Peta Kekuatan Prabowo dan Anies Jelan...  ...   
879           0  NasDem Punya Tafsir Tersendiri soal Prabowo Si...  ...   
880           0  Duet Anies-Sandi Dinilai Kecil Kemungkinan Ter...  ...   
881           1  PKS Bahagia Prabowo Bertemu Paloh: Bravo, Kian...  ...   

                                        tokenizing_all  \
0    [anies, bertemu, relawan, pendukungnya, di, au...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [bos, ppi, nilai, prabowo, dan, paloh, sudah, ...   
3    [riuh, imb, era, anies, diungkit, pdip, usai, ...   
4    [prabowo, soal, anies, siap, hadapi, rakyat, y...   
..                                                 ...   
877  [prabowo, lawan, anies, baswedan, di, pilpres,...   
878  [terkini, peta, kekuatan, prabowo, dan, anies,...   
879  [nasdem, punya, tafsir, tersendiri, soal, prab...   
880  [duet, anies, sandi, dinilai, kecil, kemungkin...   
881  [pks, bahagia, prabowo, bertemu, paloh, bravo,...   

                                 stopwords_removal_all  \
0    [anies, bertemu, relawan, pendukungnya, austra...   
1    [pks, bahagia, prabowo, bertemu, paloh, bravo,...   
2    [b

## Hasil akurasi tanpa TFIDF dan ML

In [ ]:
j = all_news['value_mean_sentil'].values.reshape(-1, 1)
accuracy_score(j,y)

0.42970521541950113

## Hasil akurasi ML tanpa TFIDF

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(j,y1, test_size=0.2 , random_state = 0)

In [ ]:
LSVM.fit(x_train,y_train)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
LR.fit(x_train, y_train)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Hasil akurasi TFIDF + Lexicon + ML

In [ ]:
df_after_lexicon_mean = df.copy()

In [ ]:
bobot_total = []

for idx, row in df.iterrows():
    # for kata, bobot in row.iteritems():
    for kata in all_news['stemming_all'][idx]:
      bobot_baris = 0
      if (kata in list(lexicon_positive.keys())):
        # print(kata)
        bobot_baris += row[kata] * lexicon_positive[kata]

      if (kata in list(lexicon_negative.keys())):
        bobot_baris += row[kata] * lexicon_negative[kata]
      print(kata, bobot_baris)
      df_after_lexicon_mean[kata][idx] = bobot_baris
        # news['score']
    print("------------------------------------------------", idx)

Streaming output truncated to the last 5000 lines.
sebut 0
lobi 0
lobi 0
inget 0
proses 0
lobi 0
paham 0
sikap 0
kondisi 0
wiranto 0
istana 0
negara 0
jl 0
veteran 0
jakarta 0
pusat 0
rabu 0
gambas 0
video 0
------------------------------------------------ 852
prabowo 0
gentar -0.13773651721123464
hadap 0
anies 0
pilpres 0
rakyat 0
milih 0
prabowo 0
harga 0
putus 0
partai 0
nasdem 0
calon 0
anies 0
baswedan 0
capres 0
pilpres 0
tum 0
partai 0
gerindra 0
gentar -0.13773651721123464
hadap 0
anies 0
rakyat 0
pilih 0.003162764184463061
------------------------------------------------ 853
warga 0
lampung 0
semut 0
pesta 0
rakyat 0
muzani 0
salam 0
prabowo 0
sekjen 0
partai 0
gerindra 0
ahmad 0
muzani 0
hadir 0
acara 0
jalan 0
sehat 0.01940127755488905
pesta 0
rakyat 0
dpd 0
gerindra 0
lampung 0
warga 0
semut 0
gelar 0
pesta 0
rakyat 0
gerindra 0
lampung 0
acara 0
gelar 0
stadion 0
pahoman 0
minggu 0
pesta 0
rakyat 0
rangkai 0
ingat 0
hut 0
partai 0
gerindra 0
februari 0
terang 0.00358986333

In [ ]:
#x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon_mean,y, test_size=0.2 , random_state = 0)
x_train , x_test , y_train , y_test = train_test_split(df_after_lexicon_mean,y1, test_size=0.2 , random_state = 0)

In [ ]:
LSVM.fit(x_train,y_train)
predictions_svm = LSVM.predict(x_test)
model_Evaluate(LSVM)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
svm_sentil_mean = {'pred': predictions_svm, 'label': y_test}
svm_sentil_mean = pd.DataFrame(svm_sentil_mean)
merge_svm_sentil_mean = svm_sentil_mean.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_svm_sentil_mean.to_csv('output_pred_meanSVMSentil.csv')

In [ ]:
merge_LR_sentil_mean['pred'].value_counts()

1    177
Name: pred, dtype: int64

In [ ]:
LR.fit(x_train, y_train)
predictions_LR = LR.predict(x_test)
model_Evaluate(LR)

              precision    recall  f1-score   support

          -1       0.00      0.00      0.00        48
           0       0.00      0.00      0.00        57
           1       0.41      1.00      0.58        72

    accuracy                           0.41       177
   macro avg       0.14      0.33      0.19       177
weighted avg       0.17      0.41      0.24       177

[[ 0  0 48]
 [ 0  0 57]
 [ 0  0 72]]


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
LR_sentil_mean = {'pred': predictions_LR, 'label': y_test}
LR_sentil_mean = pd.DataFrame(LR_sentil_mean)
merge_LR_sentil_mean = LR_sentil_mean.merge(all_news['case folding_all'], left_index=True, right_index=True)
merge_LR_sentil_mean.to_csv('output_pred_meanLRSentil.csv')

## cross validation svm

In [ ]:
scores_mean = cross_val_score(LSVM,df_after_lexicon_mean,y1, cv=5)

In [ ]:
print("Cross-validation scores: ", scores_mean)
print("Akurasi rata-rata:", scores_mean.mean())

Cross-validation scores:  [0.46892655 0.46327684 0.46590909 0.46590909 0.46590909]
Akurasi rata-rata: 0.46598613251155624


## hyperparameter svm

In [ ]:
grid_search = GridSearchCV(LSVM, param_grid_svm, cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  w

Kombinasi Hyperparameter Terbaik:
{'C': 1, 'loss': 'hinge', 'max_iter': 100, 'penalty': 'l2'}


/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


In [ ]:
# Data training dan testing
X_train, X_test, y_train, y_test = train_test_split(df_after_lexicon_mean, y, test_size=0.2, random_state=0) #digunakan random state = 0 supaya tidak berubah data yang akan diuji coba

# Inisialisasi model dengan kombinasi hyperparameter terbaik
svm_model = LinearSVC(C=1, max_iter=100, penalty='l2', loss='hinge')

# Melatih model dengan data training
svm_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = svm_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

Akurasi model: 44.63%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/svm/_base.py:1244: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


## cross validation logistic regression

In [ ]:
scores_lg_mean = cross_val_score(LR,df_after_lexicon_mean,y1, cv=5)

In [ ]:
print("Cross-validation scores: ", scores_lg_mean)
print("Akurasi rata-rata:", scores_lg_mean.mean())

Cross-validation scores:  [0.46892655 0.46327684 0.46590909 0.46590909 0.46590909]
Akurasi rata-rata: 0.46598613251155624


## hyperparameter logistic regression

In [ ]:
# Inisialisasi GridSearchCV
grid_search = GridSearchCV(logreg, param_grid_lr , cv=5)

# Melakukan grid search untuk mencari kombinasi hyperparameter terbaik
grid_search.fit(x_train, y_train)

# Menampilkan kombinasi hyperparameter terbaik
print("Kombinasi Hyperparameter Terbaik:")
print(grid_search.best_params_)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for exam

Kombinasi Hyperparameter Terbaik:
{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
# Inisialisasi model dengan kombinasi hyperparameter terbaik
logreg_model = LogisticRegression(C=10, penalty='l1', solver='liblinear')

# Melatih model dengan data training
logreg_model.fit(X_train, y_train)

# Memprediksi label untuk data testing
y_pred = logreg_model.predict(X_test)

# Evaluasi performa model
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi model: {:.2f}%".format(accuracy * 100))

Akurasi model: 47.46%


/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
